from models import *

# AUTOGENERATED FILE. DO NOT MODIFY!


################################################################################
# Category
################################################################################

class Category:

    db_model: DBCategory
    """
    The peewee database model for this Model object.
    
    Use this to access peewee database methods (e.g. insert, update, etc.).
    """

    def create_instance(self) -> DBCategory: ...
    """
    Inserts this model object as a new row into table and returns corresponding model instance.
    
    Useful for populating an AutoField primary key.
    """

################################################################################
# ItemPage
################################################################################

class ItemPage:

    db_model: DBItemPage
    """
    The peewee database model for this Model object.
    
    Use this to access peewee database methods (e.g. insert, update, etc.).
    """

    def create_instance(self) -> DBItemPage: ...
    """
    Inserts this model object as a new row into table and returns corresponding model instance.
    
    Useful for populating an AutoField primary key.
    """

################################################################################
# Item
################################################################################

class Item:

    db_model: DBItem
    """
    The peewee database model for this Model object.
    
    Use this to access peewee database methods (e.g. insert, update, etc.).
    """

    def create_instance(self) -> DBItem: ...
    """
    Inserts this model object as a new row into table and returns corresponding model instance.
    
    Useful for populating an AutoField primary key.
    """

