from models import *

# AUTOGENERATED FILE. DO NOT MODIFY!

__all__ = []


################################################################################
# Category
################################################################################


@property
def _category_db_model(self) -> DBCategory:
    """
    The peewee database model for this Model object.
    
    Use this to access peewee database methods (e.g. insert, update, etc.).
    """
    return DBCategory(
        id=self.id,
        name=self.name,
        item_count=self.item_count
    )


Category.db_model = _category_db_model


def _category_create_instance(self):
    """
    Inserts this model object as a new row into table and returns corresponding model instance.
    
    Useful for populating an AutoField primary key.
    """
    return Category.db.create(
        id=self.id,
        name=self.name,
        item_count=self.item_count
    )


Category.create_instance = _category_create_instance


################################################################################
# ItemPage
################################################################################


@property
def _itempage_db_model(self) -> DBItemPage:
    """
    The peewee database model for this Model object.
    
    Use this to access peewee database methods (e.g. insert, update, etc.).
    """
    return DBItemPage(
        category=DBCategory.get(DBCategory.id == self.category_id),
        alpha=self.alpha,
        page_num=self.page_num,
        last_updated=self.last_updated,
        succeeded=self.succeeded
    )


ItemPage.db_model = _itempage_db_model


def _itempage_create_instance(self):
    """
    Inserts this model object as a new row into table and returns corresponding model instance.
    
    Useful for populating an AutoField primary key.
    """
    return ItemPage.db.create(
        category=DBCategory.get(DBCategory.id == self.category_id),
        alpha=self.alpha,
        page_num=self.page_num,
        last_updated=self.last_updated,
        succeeded=self.succeeded
    )


ItemPage.create_instance = _itempage_create_instance


################################################################################
# Item
################################################################################


@property
def _item_db_model(self) -> DBItem:
    """
    The peewee database model for this Model object.
    
    Use this to access peewee database methods (e.g. insert, update, etc.).
    """
    return DBItem(
        id=self.id,
        category=DBCategory.get(DBCategory.id == self.category_id),
        item_page=DBItemPage.get(DBItemPage.id == self.item_page_id),
        name=self.name,
        description=self.description,
        type=self.type,
        members_only=self.members_only
    )


Item.db_model = _item_db_model


def _item_create_instance(self):
    """
    Inserts this model object as a new row into table and returns corresponding model instance.
    
    Useful for populating an AutoField primary key.
    """
    return Item.db.create(
        id=self.id,
        category=DBCategory.get(DBCategory.id == self.category_id),
        item_page=DBItemPage.get(DBItemPage.id == self.item_page_id),
        name=self.name,
        description=self.description,
        type=self.type,
        members_only=self.members_only
    )


Item.create_instance = _item_create_instance


